version: "3"
services:
  db:
    image: mysql:5.7.16
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_DATABASE: db_test
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    restart: always